### PR TITLE
Changed branch (old pull request)

### PR DESCRIPTION
**Pull request by TornaxO7**
I just added the `dev` and `stable` branch. So I can freely switch between those two branches. This pull request is just a "reponed" one to this one: https://github.com/lfilho/cosco.vim/pull/26

### CODE REVIEW

**Comment by TornaxO7** [comment]
Is it ok for you, if I open a "Cosco 2" plugin (temporary)? So I can get more Issues so the plugin can expand more and more.

I'm just thinking about it since you haven't replied after a long time now and I'm not sure if I'm going to do that.

Of course you can merge the my branch (if this time has come) and I'll close "Cosco 2" and of course I'll also credit you into the README.md.

**Comment by TornaxO7** [comment]
@lfilho Do you agree with my suggestion at the top?

**Comment by lfilho** [comment]
Hey Tornax, sorry for the late reply!

Thanks again for your continuous and tremendous effort here, appreciate it!

I didn't reply earlier because i was seen so many commits day after day, I thought you were still get the PR stable. Once that happened I was going to review it :-) 

I mainly care about two things:

**(1)**: maintaining retro compatibility -- this repo is used by a lot of people since it was created 8 years ago, it still has weekly unique clones and downloads, so I just don't want to break things for them without a good reason. If you can ensure that, I'm open to discuss whatever else: migrating the plugin to lua or whatever else you'd like to propose :-)

If the behavior you want to see in cosco conflicts with today's behavior, you might consider coding a "mode" for it: adding a new global variable, say `g:cosco_c_mode` or whatever. Then if that variable is **not** defined, then the default (current) behavior persists. If it **is** defined, your behavior kicks in. Thoughts?

**(2)**: performance and simplicity. One of the beauties of this plugin is that it performs quite within its simplicity. If we need to add more dependencies in order to add new features, I don't know, but it seems people would better of using a proper code formatter (like Prettier - https://prettier.io/ ) which is slower than cosco but also much more capable. Trying not to reinvent the wheel here.

Thoughts?

If you don't agree with the above, you can of course create your own fork and call it whatever you like. I'd be glad to link it here in this repo. 😊

**Comment by TornaxO7** [comment]
> I didn't reply earlier because i was seen so many commits day after day, I thought you were still get the PR stable. Once that happened I was going to review it :-)

Oh ok, that makes sense. It would be nice, if you could try my fork for you javascript programs so I can know if it works with javascript as well.  My friend tried it with java and he told me that it's working there as well.

> (1): maintaining retro compatibility -- this repo is used by a lot of people since it was created 8 years ago, it still has weekly unique clones and downloads, so I just don't want to break things for them without a good reason.

Ok, I can do that.

> If the behavior you want to see in cosco conflicts with today's behavior, you might consider coding a "mode" for it: adding a new global variable, say g:cosco_c_mode or whatever. Then if that variable is not defined, then the default (current) behavior persists. If it is defined, your behavior kicks in.  Thoughts?

My intention of this pull-request is the improvement of the *auto-comma-semicolon-setting* not another "cosco mode". Of course if you don't agree we can add a special variable for it but I'd rather like to name it `g:cosco_autosetter_dev` or something like that because the auto-comma-semicilon-settings shouldn't work only for C! It should work for other "semicolon-languages" as well.

> (2): performance and simplicity. One of the beauties of this plugin is that it performs quite within its simplicity. If we need to add more dependencies in order to add new features (...)

Currently Cosco has only one dependencie: [vim-polyglot](https://vimawesome.com/plugin/vim-polyglot) but I can remove it.  It's only used to check, if there's a function or not.

**Comment by TornaxO7** [comment]
Ok new update: I guess that Cosco doesn't have any dependencies anmore, but there's one problem. I don't really think that I can make it backwards compatible. What do you think should we do?

**Comment by TornaxO7** [comment]
I think I should explain it a little bit further:
My approach to let cosco decide, if we should add a comma/semicolon differs yours. So we'd have to implement *everything* again for the manual calling function.

**Comment by lfilho** [comment]
> It would be nice, if you could try my fork for you javascript programs so I can know if it works with javascript as well.

Happy to. Let me know when you are done and the PR is in a final state.

> My intention of this pull-request is the improvement of the auto-comma-semicolon-setting

I'm still not sure what those improvements are. Once you're done, it would be nice to have a "before and after" so anyone can understand the benefits/improvements you're bringing to the table. That would help with testing and possibility identifying corner cases too.

> I don't really think that I can make it backwards compatible

This is paramount, as I mentioned earlier. I don't want any user to update their plugin and have commas or semi-colons inserted/removed from different places than before the update. Unless you can really sell why we should break that retro-compatibility and break things for everyone for the sake of a greater good :-)

**Comment by TornaxO7** [comment]
> I'm still not sure what those improvements are. Once you're done, it would be nice to have a "before and after" so anyone can understand the benefits/improvements you're bringing to the table. That would help with testing and possibility identifying corner cases too.

You can take a look into the `CONTRIBUING.md` file.

**Comment by TornaxO7** [comment]
Hm... ok, so I think that I'll close this pull request, because currently I don't use it either on my own... I think that I'll keep my fork since some of my friends are using it. I hope that's fine for you :)

**Pull request closed without merging**
